[package]
name = "bonn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
finalfusion = "0.17"
pyo3 = { version = "0.15.1", features = ["extension-module"] }
numpy = "0.15"
